// nuxt/pages/lesson/index.vue
<template>
  <div>
    <div v-if="isStarted && !completed">
      <Word
        :ja="target.ja"
        :remains="remains"
        :word="target.word"
        :targetChr="targetChr"
      />
      <div class="has-text-centered">
        <canvas ref="target"></canvas>
      </div>
      <div class="has-text-centered">
        <p class="button is-black is-size-1">{{ targetChr.replace(" ", "␣").toUpperCase()  }}</p>
      </div>
      <div class="has-text-centered">
        <input
          :class="[
            'input',
            'is-large',
            'has-text-centered',
            { 'is-info': isMatch },
            { 'is-danger': isMiss },
          ]"
          type="text"
          autofocus
          v-model="inputText"
          @keyup="keyPress"
        />
      </div>
      <Images class="mt-6" :word="target.word" />
    </div>
    <div v-if="!isStarted" class="has-text-centered">
      <button v-on:click="start" class="button is-primary is-large">
        Start
      </button>
    </div>
    <div v-if="completed" class="has-text-centered">
      <p class="has-text-info">Completed!＼(^o^)／</p>
      <button class="button is-primary is-large" v-on:click="retry">
        Retry
      </button>
    </div>
    <Keyboard />
    <Debug :pressKey="pressKey" :keyCode="keyCode" :missCnt="missCnt" />
  </div>
</template>

<script>
import Lesson from "@/assets/json/lesson.json";
import * as confetti from "canvas-confetti";
export default {
  name: "index",
  data: function () {
    return {
      isStarted: false,
      inputText: "",
      target: {
        word: "",
        ja: "",
      },
      remains: "",
      targetChr: "",
      completed: false,
      missCnt: 0,
      pressKey: "",
      keyCode: "",
      isMatch: null,
      isMiss: null,
    };
  },
  created: function () {
    this.TypingData = Lesson.lesson001.words.sort(() => Math.random() - 0.5);
    window.speechSynthesis.getVoices(); // dummy call.
  },
  methods: {
    start() {
      this.isStarted = true;
      this.nextWord();
      this.speech(this.target.word);
    },
    keyPress(event) {
      if (this.checkChr(this.targetChr, event.key)) {
        this.remains = this.remains.substr(1);
        this.targetChr = this.remains.substr(0, 1);
        this.isMatch = true;
        this.isMiss = false;
        this.cracker();
        this.playDram();
      } else {
        this.inputText = this.inputText.slice(0, -1);
        this.missCnt++;
        this.isMatch = false;
        this.isMiss = true;
        this.playBeep();
      }
      if (this.remains.length === 0) {
        if (this.TypingData.length > 0) {
          this.inputText = "";
          this.nextWord();
          this.speech(this.target.word);
        } else {
          this.completed = true;
        }
      }

      this.pressKey = event.key;
      this.keyCode = event.keyCode;
    },
    checkChr(target, input) {
      if (target.toLowerCase() === input.toLowerCase()) {
        return true;
      }
      return false;
    },
    nextWord() {
      this.target = this.TypingData.shift();
      this.remains = this.target.word;
      this.targetChr = this.remains.substr(0, 1);
    },
    retry() {
      window.location.reload();
    },
    speech(text) {
      const utter = new SpeechSynthesisUtterance();
      utter.voice = window.speechSynthesis.getVoices()[41]; //Victoria
      utter.rate = 0.75;
      utter.text = text;
      window.speechSynthesis.speak(utter);
    },
    cracker() {
      confetti.create(this.$refs.target)({
        shapes: ["square"],
        particleCount: 20,
        spread: 120,
        //zIndex: 999,
        origin: {
          y: 1,
          x: 0.5,
        },
      });
    },
    playDram() {
      const dram = new Audio("/sounds/dram.mp3"); // @todo: move created
      dram.play();
    },
    playBeep() {
      const beep = new Audio("/sounds/beep.mp3"); // @todo: move created
      beep.play();
    },
  },
};
</script>
<style lang="scss"></style>

// app/src/pages/Lesson.tsx
import { useState, useEffect, useRef, useCallback } from 'react'
import { useParams } from 'react-router-dom'
import confetti from 'canvas-confetti'
import lessonData from '../data/lesson.json'
import Word from '../components/Word'
import Images from '../components/Images'
import Char from '../components/Char'
import Keyboard from '../components/Keyboard'
import Debug from '../components/Debug'

interface LessonWord {
  word: string
  ja: string
}

type LessonDataType = typeof lessonData

export default function Lesson() {
  const { id } = useParams<{ id: string }>()
  const canvasRef = useRef<HTMLCanvasElement>(null)

  const [isStarted, setIsStarted] = useState(false)
  const [isCompleted, setIsCompleted] = useState(false)
  const [target, setTarget] = useState<LessonWord>({ word: '', ja: '' })
  const [remains, setRemains] = useState('')
  const [targetChr, setTargetChr] = useState('')
  const [missCnt, setMissCnt] = useState(0)
  const [pressKey, setPressKey] = useState('')
  const [keyCode, setKeyCode] = useState(0)
  const [imageData, setImageData] = useState<LessonWord[]>([])

  // Refs to access latest state inside keyPress handler
  const remainsRef = useRef('')
  const targetChrRef = useRef('')
  const typingDataRef = useRef<LessonWord[]>([])
  const isStartedRef = useRef(false)
  const isCompletedRef = useRef(false)

  // Reset when lesson id changes
  useEffect(() => {
    if (!id) return
    const lesson = (lessonData as LessonDataType)[id as keyof LessonDataType]
    if (!lesson) return

    const words: LessonWord[] = JSON.parse(JSON.stringify(lesson.words))
    setImageData(words)

    setIsStarted(false)
    setIsCompleted(false)
    setTarget({ word: '', ja: '' })
    setRemains('')
    setTargetChr('')
    setMissCnt(0)
    setPressKey('')
    setKeyCode(0)
    typingDataRef.current = []
    isStartedRef.current = false
    isCompletedRef.current = false
    remainsRef.current = ''
    targetChrRef.current = ''

    window.speechSynthesis.getVoices() // dummy call for initialization
  }, [id])

  const speech = (text: string) => {
    const utter = new SpeechSynthesisUtterance()
    utter.voice = window.speechSynthesis.getVoices()[41]
    utter.rate = 0.75
    utter.text = text
    window.speechSynthesis.speak(utter)
  }

  const cracker = () => {
    if (!canvasRef.current) return
    confetti.create(canvasRef.current, { resize: true })({
      shapes: ['square'],
      particleCount: 20,
      spread: 120,
      origin: { y: 1, x: 0.5 },
    })
  }

  const playDram = () => new Audio('/sounds/dram.mp3').play()
  const playBeep = () => new Audio('/sounds/beep.mp3').play()

  const loadNextWord = (data: LessonWord[]) => {
    const [next, ...rest] = data
    typingDataRef.current = rest
    remainsRef.current = next.word
    targetChrRef.current = next.word.charAt(0)
    setTarget(next)
    setRemains(next.word)
    setTargetChr(next.word.charAt(0))
    return { next, rest }
  }

  const start = () => {
    if (!id) return
    const lesson = (lessonData as LessonDataType)[id as keyof LessonDataType]
    if (!lesson) return

    const words: LessonWord[] = JSON.parse(JSON.stringify(lesson.words))
    const shuffled = words.sort(() => Math.random() - 0.5)

    typingDataRef.current = shuffled
    isStartedRef.current = true
    isCompletedRef.current = false

    setTypingDataAndStart(shuffled)
  }

  const setTypingDataAndStart = (shuffled: LessonWord[]) => {
    setIsStarted(true)
    setIsCompleted(false)
    setMissCnt(0)
    setPressKey('')
    setKeyCode(0)

    const { next } = loadNextWord(shuffled)
    speech(next.word)
  }

  const retry = () => {
    if (!id) return
    const lesson = (lessonData as LessonDataType)[id as keyof LessonDataType]
    if (!lesson) return
    setImageData(JSON.parse(JSON.stringify(lesson.words)))
    start()
  }

  const keyPress = useCallback((event: KeyboardEvent) => {
    if (!isStartedRef.current || isCompletedRef.current) return

    const currentChr = targetChrRef.current
    const currentRemains = remainsRef.current
    const currentTypingData = typingDataRef.current

    if (currentChr.toLowerCase() === event.key.toLowerCase()) {
      const newRemains = currentRemains.substring(1)
      const newTargetChr = newRemains.charAt(0)

      remainsRef.current = newRemains
      targetChrRef.current = newTargetChr
      setRemains(newRemains)
      setTargetChr(newTargetChr)

      cracker()
      playDram()

      if (newRemains.length === 0) {
        if (currentTypingData.length > 0) {
          const { next } = loadNextWord(currentTypingData)
          speech(next.word)
        } else {
          isCompletedRef.current = true
          setIsCompleted(true)
        }
      }
    } else {
      setMissCnt((prev) => prev + 1)
      playBeep()
    }

    setPressKey(event.key)
    setKeyCode(event.keyCode)
  }, [])

  useEffect(() => {
    document.addEventListener('keydown', keyPress)
    return () => document.removeEventListener('keydown', keyPress)
  }, [keyPress])

  return (
    <div>
      <p className="text-sm text-gray-400 mb-2">{id}</p>

      {isStarted && !isCompleted && (
        <div>
          <Word ja={target.ja} word={target.word} />
          <Images imageData={imageData} word={target.word} />
          <div className="text-center">
            <canvas ref={canvasRef} />
          </div>
          <Char remains={remains} />
          <Keyboard targetChr={targetChr.toUpperCase()} />
          <div className="text-center mt-4">
            <button
              className="bg-blue-500 hover:bg-blue-600 text-white px-6 py-2 rounded"
              onClick={() => speech(target.word)}
            >
              再生
            </button>
          </div>
        </div>
      )}

      {!isStarted && (
        <div className="text-center mt-16">
          <button
            onClick={start}
            className="bg-blue-500 hover:bg-blue-600 text-white text-2xl px-12 py-4 rounded-lg"
          >
            Start
          </button>
        </div>
      )}

      {isCompleted && (
        <div className="text-center mt-16">
          <p className="text-blue-500 text-3xl mb-6">Completed! ＼(^o^)／</p>
          <button
            className="bg-blue-500 hover:bg-blue-600 text-white text-2xl px-12 py-4 rounded-lg"
            onClick={retry}
          >
            Retry
          </button>
        </div>
      )}

      <Debug pressKey={pressKey} keyCode={keyCode} missCnt={missCnt} />
    </div>
  )
}
